import jsPDF from 'jspdf';

interface AICommentary {
  executiveSummary: string;
  riskAssessment: string;
  scenarioCommentary: string;
  investorHighlights: string;
}

interface ModelData {
  name: string;
  project_name?: string;
  country?: string;
  start_year: number;
  end_year: number;
}

interface ScenarioData {
  scenario_name: string;
  is_base_case: boolean;
  notes?: string;
  probability?: number;
  metrics: any;
  changes: Array<{ 
    key: string;
    name: string;
    baseValue: any;
    newValue: any;
    change: number;
  }>;
}

export const generatePDF = async (
  financialData: any,
  modelData: ModelData,
  reportType: 'standard' | 'ai-assisted',
  modelInputs?: any,
  scenarios?: ScenarioData[],
  comprehensiveMetrics?: any,
  aiCommentary?: AICommentary
): Promise<void> => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;
  
  let yPosition = margin;
  let currentPage = 1;

  // Helper functions
  const checkPageBreak = (requiredHeight: number) => {
    if (yPosition + requiredHeight > pageHeight - margin - 10) {
      addPageFooter();
      pdf.addPage();
      currentPage++;
      yPosition = margin;
      return true;
    }
    return false;
  };

  const addPageFooter = () => {
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 100, 100);
    pdf.text('Generated by Financial Platform', margin, pageHeight - 7);
    pdf.text(`Page ${currentPage}`, pageWidth - margin, pageHeight - 7, { align: 'right' });
    pdf.setTextColor(0, 0, 0);
  };

  const addText = (text: string, x: number, y: number, maxWidth: number, fontSize: number = 10) => {
    pdf.setFontSize(fontSize);
    const lines = pdf.splitTextToSize(text, maxWidth);
    pdf.text(lines, x, y);
    return lines.length * (fontSize * 0.4);
  };

  const addSectionTitle = (title: string) => {
    checkPageBreak(20);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(title, margin, yPosition);
    yPosition += 8;
    pdf.setLineWidth(0.5);
    pdf.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 8;
  };

  const formatCurrency = (value: number): string => {
    return `$${Math.abs(value).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
  };

  const formatPercent = (value: number): string => {
    return `${(value * 100).toFixed(1)}%`;
  };

  const VARIABLE_FORMATS: Record<string, 'currency' | 'percentage' | 'number'> = {
    'credits_generated': 'number',
    'price_per_credit': 'currency',
    'cogs_rate': 'percentage',
    'staff_costs': 'currency',
    'mrv_costs': 'currency',
    'pdd_costs': 'currency',
    'feasibility_costs': 'currency',
    'capex': 'currency',
    'depreciation': 'currency',
    'discount_rate': 'percentage',
    'interest_rate': 'percentage',
    'income_tax_rate': 'percentage',
    'ar_rate': 'percentage',
    'ap_rate': 'percentage',
    'equity_injection': 'currency',
    'debt_draw': 'currency',
    'purchase_amount': 'currency',
    'purchase_share': 'percentage',
    'debt_duration_years': 'number',
    'issuance_flag': 'number',
  };

  const formatVariableValue = (key: string, value: number): string => {
    const format = VARIABLE_FORMATS[key] || 'number';
    
    if (format === 'currency') {
      return `$${Math.round(value).toLocaleString()}`;
    }
    if (format === 'percentage') {
      return `${value.toFixed(1)}%`;
    }
    return Math.round(value).toLocaleString();
  };

  const addDataTable = (headers: string[], rows: string[][], colWidths: number[]) => {
    const rowHeight = 6;
    const headerHeight = 7;
    
    // Check if table fits, if not add page break
    const tableHeight = headerHeight + (rows.length * rowHeight);
    checkPageBreak(tableHeight + 5);
    
    // Draw headers
    pdf.setFillColor(230, 230, 230);
    pdf.rect(margin, yPosition, contentWidth, headerHeight, 'F');
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'bold');
    
    let xPos = margin + 2;
    headers.forEach((header, i) => {
      pdf.text(header, xPos, yPosition + 5);
      xPos += colWidths[i];
    });
    
    yPosition += headerHeight;
    
    // Draw rows
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    
    rows.forEach((row, rowIndex) => {
      if (checkPageBreak(rowHeight + 2)) {
        // Redraw headers on new page
        pdf.setFillColor(230, 230, 230);
        pdf.rect(margin, yPosition, contentWidth, headerHeight, 'F');
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'bold');
        xPos = margin + 2;
        headers.forEach((header, i) => {
          pdf.text(header, xPos, yPosition + 5);
          xPos += colWidths[i];
        });
        yPosition += headerHeight;
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(8);
      }
      
      // Alternate row colors
      if (rowIndex % 2 === 1) {
        pdf.setFillColor(248, 248, 248);
        pdf.rect(margin, yPosition, contentWidth, rowHeight, 'F');
      }
      
      xPos = margin + 2;
      row.forEach((cell, i) => {
        const align = i === 0 ? 'left' : 'right';
        if (align === 'right') {
          pdf.text(cell, xPos + colWidths[i] - 4, yPosition + 4, { align: 'right' });
        } else {
          pdf.text(cell, xPos, yPosition + 4);
        }
        xPos += colWidths[i];
      });
      
      yPosition += rowHeight;
    });
    
    yPosition += 5;
  };

  // ========== COVER PAGE ==========
  pdf.setFontSize(28);
  pdf.setFont('helvetica', 'bold');
  const reportTitle = reportType === 'ai-assisted' ? 'AI-Assisted Financial Report' : 'Comprehensive Financial Report';
  pdf.text(reportTitle, pageWidth / 2, 50, { align: 'center' });

  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'normal');
  pdf.text(modelData.project_name || modelData.name, pageWidth / 2, 75, { align: 'center' });
  
  pdf.setFontSize(12);
  pdf.setTextColor(60, 60, 60);
  pdf.text(`Country: ${modelData.country || 'Not specified'}`, pageWidth / 2, 95, { align: 'center' });
  pdf.text(`Projection Period: ${modelData.start_year} - ${modelData.end_year}`, pageWidth / 2, 105, { align: 'center' });
  pdf.text(`Report Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, 115, { align: 'center' });
  pdf.setTextColor(0, 0, 0);

  addPageFooter();
  pdf.addPage();
  currentPage++;
  yPosition = margin;

  // ========== EXECUTIVE SUMMARY ==========
  addSectionTitle('Executive Summary');
  
  if (reportType === 'ai-assisted' && aiCommentary) {
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    const summaryHeight = addText(aiCommentary.executiveSummary, margin, yPosition, contentWidth, 10);
    yPosition += summaryHeight + 10;
  } else {
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`This report provides a comprehensive financial analysis for ${modelData.project_name || modelData.name}`, margin, yPosition);
    yPosition += 5;
    pdf.text(`over the ${modelData.end_year - modelData.start_year + 1}-year projection period from ${modelData.start_year} to ${modelData.end_year}.`, margin, yPosition);
    yPosition += 10;
  }

  // Key Metrics Dashboard
  if (comprehensiveMetrics) {
    checkPageBreak(50);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Key Financial Metrics', margin, yPosition);
    yPosition += 8;
    
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    const metricsData = [
      ['Equity NPV:', formatCurrency(comprehensiveMetrics.returns?.equity?.npv || 0)],
      ['Equity IRR:', formatPercent(comprehensiveMetrics.returns?.equity?.irr || 0)],
      ['Project NPV:', formatCurrency(comprehensiveMetrics.returns?.project?.npv || 0)],
      ['Project IRR:', formatPercent(comprehensiveMetrics.returns?.project?.irr || 0)],
      ['Payback Period:', `${(comprehensiveMetrics.returns?.equity?.payback || 0).toFixed(1)} years`],
      ['Min DSCR:', (comprehensiveMetrics.debt?.minDSCR || 0).toFixed(2)],
      ['Peak Funding:', formatCurrency(comprehensiveMetrics.liquidity?.peakFundingNeed || 0)],
    ];
    
    metricsData.forEach(([label, value]) => {
      pdf.setFont('helvetica', 'normal');
      pdf.text(label, margin + 5, yPosition);
      pdf.setFont('helvetica', 'bold');
      pdf.text(value, margin + 70, yPosition);
      yPosition += 6;
    });
    yPosition += 5;
  }

  // ========== MODEL INPUTS ==========
  if (modelInputs) {
    addSectionTitle('Model Inputs & Assumptions');
    
    // Operational Metrics
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Operational Metrics', margin, yPosition);
    yPosition += 7;
    
    const opHeaders = ['Year', 'Credits Generated', 'Price/Credit', 'Issuance'];
    const opColWidths = [25, 40, 40, 35];
    const opRows: string[][] = [];
    
    modelInputs.years.forEach((year: number, idx: number) => {
      opRows.push([
        year.toString(),
        (modelInputs.credits_generated?.[idx] || 0).toLocaleString(),
        formatCurrency(modelInputs.price_per_credit?.[idx] || 0),
        modelInputs.issuance_flag?.[idx] ? 'Yes' : 'No'
      ]);
    });
    
    addDataTable(opHeaders, opRows, opColWidths);
    
    // Expenses
    checkPageBreak(40);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Annual Expenses', margin, yPosition);
    yPosition += 7;
    
    const expHeaders = ['Year', 'Feasibility', 'PDD', 'MRV', 'Staff', 'Depreciation', 'CAPEX'];
    const expColWidths = [20, 25, 25, 25, 25, 28, 32];
    const expRows: string[][] = [];
    
    modelInputs.years.forEach((year: number, idx: number) => {
      expRows.push([
        year.toString(),
        formatCurrency(Math.abs(modelInputs.feasibility_costs?.[idx] || 0)),
        formatCurrency(Math.abs(modelInputs.pdd_costs?.[idx] || 0)),
        formatCurrency(Math.abs(modelInputs.mrv_costs?.[idx] || 0)),
        formatCurrency(Math.abs(modelInputs.staff_costs?.[idx] || 0)),
        formatCurrency(Math.abs(modelInputs.depreciation?.[idx] || 0)),
        formatCurrency(Math.abs(modelInputs.capex?.[idx] || 0))
      ]);
    });
    
    addDataTable(expHeaders, expRows, expColWidths);
    
    // Rates & Financing Assumptions
    checkPageBreak(40);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Rates & Financing Assumptions', margin, yPosition);
    yPosition += 7;
    
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    const assumptions = [
      ['COGS Rate:', formatPercent(modelInputs.cogs_rate || 0)],
      ['Tax Rate:', formatPercent(modelInputs.income_tax_rate || 0)],
      ['AR Rate:', formatPercent(modelInputs.ar_rate || 0)],
      ['AP Rate:', formatPercent(modelInputs.ap_rate || 0)],
      ['Interest Rate:', formatPercent(modelInputs.interest_rate || 0)],
      ['Debt Duration:', `${modelInputs.debt_duration_years || 0} years`],
      ['Discount Rate:', formatPercent(modelInputs.discount_rate || 0)],
      ['Initial Equity (t0):', formatCurrency(modelInputs.initial_equity_t0 || 0)],
    ];
    
    assumptions.forEach(([label, value]) => {
      pdf.text(label, margin + 5, yPosition);
      pdf.setFont('helvetica', 'bold');
      pdf.text(value, margin + 70, yPosition);
      pdf.setFont('helvetica', 'normal');
      yPosition += 6;
    });
    yPosition += 10;
  }

  // ========== FINANCIAL STATEMENTS ==========
  if (financialData) {
    addSectionTitle('Financial Statements');
    
    // Income Statement
    if (financialData.incomeStatements && financialData.incomeStatements.length > 0) {
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Income Statement', margin, yPosition);
      yPosition += 7;
      
      const years = financialData.incomeStatements.map((stmt: any) => stmt.year);
      const incHeaders = ['Line Item', ...years.map((y: number) => y.toString())];
      const incColWidth = Math.min(30, contentWidth / (years.length + 1));
      const incColWidths = [50, ...years.map(() => incColWidth)];
      
      const incRows: string[][] = [
        ['Total Revenue', ...financialData.incomeStatements.map((s: any) => formatCurrency(s.total_revenue || 0))],
        ['COGS', ...financialData.incomeStatements.map((s: any) => formatCurrency(Math.abs(s.cogs || 0)))],
        ['Gross Profit', ...financialData.incomeStatements.map((s: any) => formatCurrency(s.gross_profit || 0))],
        ['Operating Expenses', ...financialData.incomeStatements.map((s: any) => formatCurrency(Math.abs(s.total_opex || 0)))],
        ['EBITDA', ...financialData.incomeStatements.map((s: any) => formatCurrency(s.ebitda || 0))],
        ['Depreciation', ...financialData.incomeStatements.map((s: any) => formatCurrency(Math.abs(s.depreciation || 0)))],
        ['EBIT', ...financialData.incomeStatements.map((s: any) => formatCurrency(s.ebit || 0))],
        ['Interest Expense', ...financialData.incomeStatements.map((s: any) => formatCurrency(Math.abs(s.interest_expense || 0)))],
        ['EBT', ...financialData.incomeStatements.map((s: any) => formatCurrency(s.ebt || 0))],
        ['Tax', ...financialData.incomeStatements.map((s: any) => formatCurrency(Math.abs(s.tax || 0)))],
        ['Net Income', ...financialData.incomeStatements.map((s: any) => formatCurrency(s.net_income || 0))],
      ];
      
      addDataTable(incHeaders, incRows, incColWidths);
    }
    
    // Balance Sheet
    if (financialData.balanceSheets && financialData.balanceSheets.length > 0) {
      checkPageBreak(50);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Balance Sheet', margin, yPosition);
      yPosition += 7;
      
      const years = financialData.balanceSheets.map((stmt: any) => stmt.year);
      const bsHeaders = ['Line Item', ...years.map((y: number) => y.toString())];
      const bsColWidth = Math.min(30, contentWidth / (years.length + 1));
      const bsColWidths = [50, ...years.map(() => bsColWidth)];
      
      const bsRows: string[][] = [
        ['Cash', ...financialData.balanceSheets.map((s: any) => formatCurrency(s.cash || 0))],
        ['Accounts Receivable', ...financialData.balanceSheets.map((s: any) => formatCurrency(s.accounts_receivable || 0))],
        ['Total Assets', ...financialData.balanceSheets.map((s: any) => formatCurrency(s.total_assets || 0))],
        ['Accounts Payable', ...financialData.balanceSheets.map((s: any) => formatCurrency(s.accounts_payable || 0))],
        ['Debt', ...financialData.balanceSheets.map((s: any) => formatCurrency(s.debt || 0))],
        ['Total Liabilities', ...financialData.balanceSheets.map((s: any) => formatCurrency(s.total_liabilities || 0))],
        ['Equity', ...financialData.balanceSheets.map((s: any) => formatCurrency(s.equity || 0))],
        ['Total L+E', ...financialData.balanceSheets.map((s: any) => formatCurrency(s.total_liabilities_equity || 0))],
      ];
      
      addDataTable(bsHeaders, bsRows, bsColWidths);
    }
    
    // Cash Flow Statement
    if (financialData.cashFlowStatements && financialData.cashFlowStatements.length > 0) {
      checkPageBreak(50);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Cash Flow Statement', margin, yPosition);
      yPosition += 7;
      
      const years = financialData.cashFlowStatements.map((stmt: any) => stmt.year);
      const cfHeaders = ['Line Item', ...years.map((y: number) => y.toString())];
      const cfColWidth = Math.min(30, contentWidth / (years.length + 1));
      const cfColWidths = [50, ...years.map(() => cfColWidth)];
      
      const cfRows: string[][] = [
        ['Net Income', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.net_income || 0))],
        ['Depreciation', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.depreciation || 0))],
        ['Change in AR', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.change_ar || 0))],
        ['Change in AP', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.change_ap || 0))],
        ['CFO', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.cfo || 0))],
        ['CAPEX', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.capex || 0))],
        ['CFI', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.cfi || 0))],
        ['Equity Injection', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.equity_injection || 0))],
        ['Debt Draw', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.debt_draw || 0))],
        ['Debt Repay', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.debt_repay || 0))],
        ['CFF', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.cff || 0))],
        ['Net Cash Change', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.net_cash_change || 0))],
        ['Ending Cash', ...financialData.cashFlowStatements.map((s: any) => formatCurrency(s.cash_end || 0))],
      ];
      
      addDataTable(cfHeaders, cfRows, cfColWidths);
    }
    
    // Debt Schedule
    if (financialData.debtSchedule && financialData.debtSchedule.length > 0) {
      checkPageBreak(40);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Debt Schedule', margin, yPosition);
      yPosition += 7;
      
      const years = financialData.debtSchedule.map((stmt: any) => stmt.year);
      const debtHeaders = ['Line Item', ...years.map((y: number) => y.toString())];
      const debtColWidth = Math.min(30, contentWidth / (years.length + 1));
      const debtColWidths = [50, ...years.map(() => debtColWidth)];
      
      const debtRows: string[][] = [
        ['Beginning Balance', ...financialData.debtSchedule.map((s: any) => formatCurrency(s.beginning_balance || 0))],
        ['Draw', ...financialData.debtSchedule.map((s: any) => formatCurrency(s.draw || 0))],
        ['Principal Payment', ...financialData.debtSchedule.map((s: any) => formatCurrency(Math.abs(s.principal_payment || 0)))],
        ['Ending Balance', ...financialData.debtSchedule.map((s: any) => formatCurrency(s.ending_balance || 0))],
        ['Interest Expense', ...financialData.debtSchedule.map((s: any) => formatCurrency(Math.abs(s.interest_expense || 0)))],
        ['DSCR', ...financialData.debtSchedule.map((s: any) => (s.dscr || 0).toFixed(2))],
      ];
      
      addDataTable(debtHeaders, debtRows, debtColWidths);
    }
    
    // Carbon Stream
    if (financialData.carbonStream && financialData.carbonStream.length > 0) {
      checkPageBreak(40);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Carbon Stream', margin, yPosition);
      yPosition += 7;
      
      const years = financialData.carbonStream.map((stmt: any) => stmt.year);
      const carbonHeaders = ['Line Item', ...years.map((y: number) => y.toString())];
      const carbonColWidth = Math.min(30, contentWidth / (years.length + 1));
      const carbonColWidths = [50, ...years.map(() => carbonColWidth)];
      
      const carbonRows: string[][] = [
        ['Credits Generated', ...financialData.carbonStream.map((s: any) => (s.credits_generated || 0).toLocaleString())],
        ['Credits Issued', ...financialData.carbonStream.map((s: any) => (s.credits_issued || 0).toLocaleString())],
        ['Purchase %', ...financialData.carbonStream.map((s: any) => formatPercent(s.purchase_percent || 0))],
        ['Purchased Credits', ...financialData.carbonStream.map((s: any) => (s.purchased_credits || 0).toLocaleString())],
        ['Purchase Amount', ...financialData.carbonStream.map((s: any) => formatCurrency(s.purchase_amount || 0))],
      ];
      
      addDataTable(carbonHeaders, carbonRows, carbonColWidths);
    }
    
    // Free Cash Flow
    if (financialData.freeCashFlow && financialData.freeCashFlow.length > 0) {
      checkPageBreak(40);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Free Cash Flow to Equity', margin, yPosition);
      yPosition += 7;
      
      const years = financialData.freeCashFlow.map((stmt: any) => stmt.year);
      const fcfHeaders = ['Line Item', ...years.map((y: number) => y.toString())];
      const fcfColWidth = Math.min(30, contentWidth / (years.length + 1));
      const fcfColWidths = [50, ...years.map(() => fcfColWidth)];
      
      const fcfRows: string[][] = [
        ['Net Income', ...financialData.freeCashFlow.map((s: any) => formatCurrency(s.net_income || 0))],
        ['Depreciation', ...financialData.freeCashFlow.map((s: any) => formatCurrency(s.depreciation || 0))],
        ['Change in NWC', ...financialData.freeCashFlow.map((s: any) => formatCurrency(s.change_nwc || 0))],
        ['CAPEX', ...financialData.freeCashFlow.map((s: any) => formatCurrency(s.capex || 0))],
        ['Net Borrowing', ...financialData.freeCashFlow.map((s: any) => formatCurrency(s.net_borrowing || 0))],
        ['FCF to Equity', ...financialData.freeCashFlow.map((s: any) => formatCurrency(s.fcf_equity || 0))],
      ];
      
      addDataTable(fcfHeaders, fcfRows, fcfColWidths);
    }
  }

  // ========== COMPREHENSIVE METRICS ==========
  if (comprehensiveMetrics) {
    addSectionTitle('Comprehensive Financial Metrics');
    
    // Returns Metrics
    if (comprehensiveMetrics.returns) {
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Returns Metrics', margin, yPosition);
      yPosition += 7;
      
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      const returnsData = [
        ['Equity NPV:', formatCurrency(comprehensiveMetrics.returns.equity?.npv || 0)],
        ['Equity IRR:', formatPercent(comprehensiveMetrics.returns.equity?.irr || 0)],
        ['Equity MIRR:', formatPercent(comprehensiveMetrics.returns.equity?.mirr || 0)],
        ['Equity Payback:', `${(comprehensiveMetrics.returns.equity?.payback || 0).toFixed(1)} years`],
        ['Project NPV:', formatCurrency(comprehensiveMetrics.returns.project?.npv || 0)],
        ['Project IRR:', formatPercent(comprehensiveMetrics.returns.project?.irr || 0)],
        ['Project MIRR:', formatPercent(comprehensiveMetrics.returns.project?.mirr || 0)],
        ['Project Payback:', `${(comprehensiveMetrics.returns.project?.payback || 0).toFixed(1)} years`],
      ];
      
      returnsData.forEach(([label, value]) => {
        checkPageBreak(7);
        pdf.text(label, margin + 5, yPosition);
        pdf.setFont('helvetica', 'bold');
        pdf.text(value, margin + 70, yPosition);
        pdf.setFont('helvetica', 'normal');
        yPosition += 6;
      });
      yPosition += 5;
    }
    
    // Profitability & Unit Economics
    checkPageBreak(30);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Profitability & Unit Economics', margin, yPosition);
    yPosition += 7;
    
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    if (comprehensiveMetrics.profitability) {
      const profitData = [
        ['Avg Gross Margin:', formatPercent(comprehensiveMetrics.profitability.avgGrossMargin || 0)],
        ['Avg EBITDA Margin:', formatPercent(comprehensiveMetrics.profitability.avgEbitdaMargin || 0)],
        ['Avg Net Margin:', formatPercent(comprehensiveMetrics.profitability.avgNetMargin || 0)],
      ];
      profitData.forEach(([label, value]) => {
        checkPageBreak(7);
        pdf.text(label, margin + 5, yPosition);
        pdf.setFont('helvetica', 'bold');
        pdf.text(value, margin + 70, yPosition);
        pdf.setFont('helvetica', 'normal');
        yPosition += 6;
      });
    }
    
    if (comprehensiveMetrics.unitEconomics) {
      const unitData = [
        ['Avg Price/Credit:', formatCurrency(comprehensiveMetrics.unitEconomics.avgPricePerCredit || 0)],
        ['Avg COGS/Credit:', formatCurrency(comprehensiveMetrics.unitEconomics.avgCogsPerCredit || 0)],
        ['LCOC:', formatCurrency(comprehensiveMetrics.unitEconomics.lcoc || 0)],
      ];
      unitData.forEach(([label, value]) => {
        checkPageBreak(7);
        pdf.text(label, margin + 5, yPosition);
        pdf.setFont('helvetica', 'bold');
        pdf.text(value, margin + 70, yPosition);
        pdf.setFont('helvetica', 'normal');
        yPosition += 6;
      });
    }
    yPosition += 5;
    
    // Debt & Liquidity
    checkPageBreak(25);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Debt & Liquidity Metrics', margin, yPosition);
    yPosition += 7;
    
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    const debtLiqData = [
      ['Min DSCR:', (comprehensiveMetrics.debt?.minDSCR || 0).toFixed(2)],
      ['Avg DSCR:', (comprehensiveMetrics.debt?.avgDSCR || 0).toFixed(2)],
      ['Peak Funding Need:', formatCurrency(comprehensiveMetrics.liquidity?.peakFundingNeed || 0)],
      ['Ending Cash:', formatCurrency(comprehensiveMetrics.liquidity?.endingCash || 0)],
    ];
    
    debtLiqData.forEach(([label, value]) => {
      checkPageBreak(7);
      pdf.text(label, margin + 5, yPosition);
      pdf.setFont('helvetica', 'bold');
      pdf.text(value, margin + 70, yPosition);
      pdf.setFont('helvetica', 'normal');
      yPosition += 6;
    });
    yPosition += 5;
    
    // Carbon Metrics
    if (comprehensiveMetrics.carbon) {
      checkPageBreak(25);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Carbon Metrics', margin, yPosition);
      yPosition += 7;
      
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      const carbonData = [
        ['Total Credits Generated:', (comprehensiveMetrics.carbon.totalCreditsGenerated || 0).toLocaleString()],
        ['Total Credits Issued:', (comprehensiveMetrics.carbon.totalCreditsIssued || 0).toLocaleString()],
        ['Total Credits Delivered:', (comprehensiveMetrics.carbon.totalCreditsDelivered || 0).toLocaleString()],
      ];
      
      carbonData.forEach(([label, value]) => {
        checkPageBreak(7);
        pdf.text(label, margin + 5, yPosition);
        pdf.setFont('helvetica', 'bold');
        pdf.text(value, margin + 80, yPosition);
        pdf.setFont('helvetica', 'normal');
        yPosition += 6;
      });
      yPosition += 5;
    }
  }

  // ========== SCENARIO ANALYSIS ==========
  if (scenarios && scenarios.length > 0) {
    addSectionTitle('Scenario Analysis');
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`${scenarios.length} scenario(s) analyzed`, margin, yPosition);
    yPosition += 10;
    
    scenarios.forEach((scenario, index) => {
      checkPageBreak(40);
      
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'bold');
      const scenarioTitle = `${index + 1}. ${scenario.scenario_name}${scenario.is_base_case ? ' (Base Case)' : ''}`;
      pdf.text(scenarioTitle, margin, yPosition);
      yPosition += 7;
      
      if (scenario.probability) {
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'normal');
        pdf.text(`Probability: ${formatPercent(scenario.probability)}`, margin + 5, yPosition);
        yPosition += 6;
      }
      
      // Key metrics for scenario
      if (scenario.metrics) {
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'normal');
        const scenMetrics = [
          ['Equity NPV:', formatCurrency(scenario.metrics.returns?.equity?.npv || 0)],
          ['Equity IRR:', formatPercent(scenario.metrics.returns?.equity?.irr || 0)],
          ['Project NPV:', formatCurrency(scenario.metrics.returns?.project?.npv || 0)],
        ];
        
        scenMetrics.forEach(([label, value]) => {
          checkPageBreak(7);
          pdf.text(label, margin + 5, yPosition);
          pdf.setFont('helvetica', 'bold');
          pdf.text(value, margin + 50, yPosition);
          pdf.setFont('helvetica', 'normal');
          yPosition += 6;
        });
      }
      
      // Variable changes
      if (scenario.changes && scenario.changes.length > 0) {
        checkPageBreak(20);
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'bold');
        pdf.text(`Variables Changed: ${scenario.changes.length}`, margin + 5, yPosition);
        yPosition += 7;
        
        scenario.changes.forEach((change) => {
          checkPageBreak(10);
          pdf.setFontSize(8);
          pdf.setFont('helvetica', 'bold');
          pdf.text(change.name, margin + 10, yPosition);
          yPosition += 5;
          
          pdf.setFont('helvetica', 'normal');
          const changeSign = change.change >= 0 ? '+' : '';
          pdf.text(`${formatVariableValue(change.key, change.baseValue)} → ${formatVariableValue(change.key, change.newValue)}  (${changeSign}${(change.change * 100).toFixed(1)}%)`, margin + 15, yPosition);
          yPosition += 6;
        });
        yPosition += 3;
      }
      
      // Impact Summary (show percentage change from base case)
      const baseCase = scenarios.find(s => s.is_base_case);
      if (!scenario.is_base_case && baseCase && scenario.metrics && baseCase.metrics) {
        checkPageBreak(20);
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Impact Summary:', margin + 5, yPosition);
        yPosition += 7;
        
        pdf.setFont('helvetica', 'normal');
        const baseNPV = baseCase.metrics.returns?.equity?.npv || 0;
        const scenarioNPV = scenario.metrics.returns?.equity?.npv || 0;
        const npvChange = baseNPV !== 0 ? ((scenarioNPV - baseNPV) / Math.abs(baseNPV)) * 100 : 0;
        
        const baseIRR = baseCase.metrics.returns?.equity?.irr || 0;
        const scenarioIRR = scenario.metrics.returns?.equity?.irr || 0;
        const irrChange = baseIRR !== 0 ? ((scenarioIRR - baseIRR) / Math.abs(baseIRR)) * 100 : 0;
        
        const baseRevenue = baseCase.metrics.profitability?.totalRevenue || 0;
        const scenarioRevenue = scenario.metrics.profitability?.totalRevenue || 0;
        const revenueChange = baseRevenue !== 0 ? ((scenarioRevenue - baseRevenue) / Math.abs(baseRevenue)) * 100 : 0;
        
        const impactData = [
          ['NPV:', `${npvChange >= 0 ? '+' : ''}${npvChange.toFixed(1)}%`],
          ['IRR:', `${irrChange >= 0 ? '+' : ''}${irrChange.toFixed(1)}%`],
          ['Revenue:', `${revenueChange >= 0 ? '+' : ''}${revenueChange.toFixed(1)}%`],
        ];
        
        impactData.forEach(([label, value]) => {
          checkPageBreak(6);
          pdf.text(label, margin + 10, yPosition);
          pdf.setFont('helvetica', 'bold');
          pdf.text(value, margin + 50, yPosition);
          pdf.setFont('helvetica', 'normal');
          yPosition += 6;
        });
        yPosition += 3;
      }
      
      // Notes
      if (scenario.notes) {
        checkPageBreak(15);
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'italic');
        pdf.text('Notes:', margin + 5, yPosition);
        yPosition += 6;
        pdf.setFont('helvetica', 'normal');
        const notesHeight = addText(scenario.notes, margin + 10, yPosition, contentWidth - 10, 9);
        yPosition += notesHeight + 5;
      }
      
      yPosition += 5;
    });
    
    // Probability-weighted metrics
    const withProbabilities = scenarios.filter(s => s.probability && s.probability > 0);
    if (withProbabilities.length > 0) {
      checkPageBreak(30);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Probability-Weighted Metrics', margin, yPosition);
      yPosition += 7;
      
      const totalProb = withProbabilities.reduce((sum, s) => sum + (s.probability || 0), 0);
      const weightedEquityNPV = withProbabilities.reduce((sum, s) => sum + (s.metrics?.returns?.equity?.npv || 0) * (s.probability || 0), 0);
      const weightedEquityIRR = withProbabilities.reduce((sum, s) => sum + (s.metrics?.returns?.equity?.irr || 0) * (s.probability || 0), 0);
      
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Total Probability: ${formatPercent(totalProb)}`, margin + 5, yPosition);
      yPosition += 6;
      pdf.text('Weighted Equity NPV:', margin + 5, yPosition);
      pdf.setFont('helvetica', 'bold');
      pdf.text(formatCurrency(weightedEquityNPV), margin + 70, yPosition);
      yPosition += 6;
      pdf.setFont('helvetica', 'normal');
      pdf.text('Weighted Equity IRR:', margin + 5, yPosition);
      pdf.setFont('helvetica', 'bold');
      pdf.text(formatPercent(weightedEquityIRR), margin + 70, yPosition);
      yPosition += 10;
    }
  }

  // ========== AI COMMENTARY (AI-assisted reports only) ==========
  if (reportType === 'ai-assisted' && aiCommentary) {
    addSectionTitle('Risk Assessment');
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    const riskHeight = addText(aiCommentary.riskAssessment, margin, yPosition, contentWidth, 10);
    yPosition += riskHeight + 10;
    
    addSectionTitle('Scenario Commentary');
    const scenarioHeight = addText(aiCommentary.scenarioCommentary, margin, yPosition, contentWidth, 10);
    yPosition += scenarioHeight + 10;
    
    addSectionTitle('Investment Highlights');
    const highlightsHeight = addText(aiCommentary.investorHighlights, margin, yPosition, contentWidth, 10);
    yPosition += highlightsHeight + 10;
  }

  // Footer on last page
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
    pdf.text('Generated by Financial Platform', margin, pageHeight - 10);
  }

  // Save the PDF
  const fileName = `${modelData.project_name || modelData.name}_${reportType}_report_${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(fileName);
};