// If you export your header config, snapshot it to freeze the contract
import { HEADERS } from "@/lib/utils/exportUtils";

describe("Export Parity Guards", () => {
  it("CSV/Excel headers remain stable", () => {
    expect(HEADERS).toMatchInlineSnapshot(`
{
  "balanceSheet": [
    "year",
    "cash",
    "accounts_receivable",
    "ppe_net",
    "total_assets",
    "accounts_payable",
    "unearned_revenue",
    "debt_balance",
    "total_liabilities",
    "retained_earnings",
    "shareholder_equity",
    "equity_injection",
    "total_equity",
    "total_liabilities_equity",
    "balance_check",
  ],
  "carbonStream": [
    "year",
    "purchase_amount",
    "purchased_credits",
    "implied_purchase_price",
  ],
  "cashFlow": [
    "year",
    "net_income",
    "depreciation",
    "decrease_in_ar",
    "increase_in_ap",
    "operating_cash_flow",
    "capex",
    "investing_cash_flow",
    "debt_financing",
    "debt_repayments",
    "change_unearned_revenue",
    "equity_injection",
    "financing_cash_flow",
    "cash_start",
    "net_change_cash",
    "cash_end",
  ],
  "debtSchedule": [
    "year",
    "beginning_balance",
    "draw",
    "principal_payment",
    "ending_balance",
    "interest_expense",
    "dscr",
  ],
  "freeCashFlow": [
    "year",
    "net_income",
    "depreciation_addback",
    "change_working_capital",
    "capex",
    "net_borrowing",
    "fcf_to_equity",
  ],
  "incomeStatement": [
    "year",
    "credits_generated",
    "credits_issued",
    "price_per_credit",
    "purchased_credits",
    "implied_purchase_price",
    "spot_revenue",
    "pre_purchase_revenue",
    "total_revenue",
    "cogs",
    "gross_profit",
    "feasibility_costs",
    "pdd_costs",
    "mrv_costs",
    "staff_costs",
    "opex_total",
    "ebitda",
    "depreciation",
    "ebit",
    "interest_expense",
    "earnings_before_tax",
    "income_tax",
    "net_income",
  ],
}
`);
  });
});