// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmeapvxhkhmtzwscukfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtZWFwdnhoa2htdHp3c2N1a2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTk1MDYsImV4cCI6MjA3NDIzNTUwNn0.l531S-u3RkxDgQfpZjwSDlCXVNUSJcM1kFpQR47B7vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});